name: Run all steps (nightly)

on:
  schedule:
    - cron: 20 23 * * *

jobs:
  run_all_steps:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Run All Steps (1-3)
      run: |
        python run_all_steps.py

    - name: Git Config
      run: |
        git config user.name 'Nya Îžlimu'
        git config user.email 'info@elimu.ai'
    - name: Git Commit
      run: |
        git add step1_prepare/*.csv
        git commit -m 'chore(ml): run all steps' --allow-empty
    - name: Git Push
      run: |
        git push
